name: cafe_sabor
description: A new Flutter project.
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  dartz: ^0.10.1
  lottie: ^2.7.0
  get_it: ^7.6.4
  flutter_bloc: ^8.1.3
  flutter_lints: ^3.0.1
  firebase_auth: ^4.14.0
  firebase_core: ^2.22.0
  cloud_firestore: ^4.13.1
  flutter_native_splash: ^2.3.6
  image_picker_loading_jm: ^0.0.4
  cafe_sabor_ui_kit:
    path: ../cafeSaborUiKit

flutter:
  uses-material-design: true


  assets:
    - assets/image/
    - assets/lottie/

  fonts:
    - family: SaborFont
      fonts:
        - asset: assets/fonts/Sabor-Font.otf

    - family: Borna
      fonts:
        - asset: assets/fonts/borna-medium.otf

