name: cafe_sabor
description: A new Flutter project.
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  dartz: ^0.10.1
  lottie: ^3.1.0
  get_it: ^7.6.7
  shimmer: ^3.0.0
  flutter_bloc: ^8.1.4
  image_picker: ^1.0.7
  flutter_lints: ^3.0.1
  firebase_auth: ^4.16.0
  firebase_core: ^2.25.4
  cloud_firestore: ^4.15.5
  phone_form_field: ^9.1.0
  sliding_up_panel: ^2.0.0+1
  shared_preferences: ^2.2.2
  flutter_native_splash: ^2.3.6
  tiktok_transitions_jm: ^0.0.4
  image_picker_loading_jm: ^0.0.9
  cafe_sabor_ui_kit:
    git:
      url: https://github.com/JeisonManuelVargas/cafeSaborUiKit

flutter:
  uses-material-design: true


  assets:
    - assets/image/
    - assets/lottie/
    - assets/icons/

  fonts:
    - family: SaborFont
      fonts:
        - asset: assets/fonts/Sabor-Font.otf

    - family: Borna
      fonts:
        - asset: assets/fonts/borna-medium.otf

