name: build feature branch

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.8'

      - name: Flutter clean
        run: flutter clean

      - name: Flutter pub get
        run: flutter pub get

      - name: Configure Firebase
        run: echo "${{ secrets.FIREBASE_CONFIG }}" > android/app/google-services.json

      - name: Flutter build apk
        run: flutter build apk